### ISSUE TITLE
PTP library as server

### ISSUE THREAD

**Issue by Bagh418** [leifclaesson/ESP1588#1]
Hi every body,
I want to know that is it possible to use this lib as PTP server? For one of my project i need to use PTP server on my esp32 and i don`t have any data about how to implement PTP server on esp. 
Hope somebody can help me :(
Thanks a lot

**Comment by leifclaesson** [comment]
This library is a PTP client. 
It is possible to write a PTP server for ESP32, but that would be a different library altogether.
In order to be useful, it would have to be a PTP _grand master_ and that in turn needs external synchronization, such as GPS.
There are already many existing PTP clock implementations in both hardware and software for different platforms, and since you only need _one_ for an entire network of clients, the low price of an ESP32 compared to for example a Raspberry Pi does not make a big difference in the entire system cost, and so the development time and effort becomes the bigger factor.

But, if you want to write one, have at it. :)
